from curriculum.types import Lesson

LESSONS: list[Lesson] = [
    {
        "id": "unit1_lesson1",
        "unit": 1,
        "order": 1,
        "title": "Greetings",
        "title_ja": "挨拶",
        "level": "N5",
        "type": "conversation",
        "description": "Learn basic Japanese greetings at the airport immigration counter",
        "objectives": [
            "Greet the immigration officer",
            "Ask and answer 'How are you?'",
            "Say thank you and goodbye politely",
        ],
        "vocabulary": [
            {"word": "こんにちは", "reading": "こんにちは", "romaji": "Konnichiwa", "meaning": "hello (daytime)", "example": "こんにちは、元気ですか？", "example_translation": "Hello, how are you?"},
            {"word": "おはようございます", "reading": "おはようございます", "romaji": "Ohayou gozaimasu", "meaning": "good morning (polite)", "example": "おはようございます。いいお天気ですね。", "example_translation": "Good morning, nice weather isn't it."},
            {"word": "こんばんは", "reading": "こんばんは", "romaji": "Konbanwa", "meaning": "good evening", "example": "こんばんは、元気ですか？", "example_translation": "Good evening, how are you?"},
            {"word": "元気", "reading": "げんき", "romaji": "Genki", "meaning": "healthy/energetic", "example": "はい、元気です。", "example_translation": "Yes, I'm fine."},
            {"word": "ありがとうございます", "reading": "ありがとうございます", "romaji": "Arigatou gozaimasu", "meaning": "thank you (polite)", "example": "ありがとうございます！", "example_translation": "Thank you!"},
            {"word": "さようなら", "reading": "さようなら", "romaji": "Sayounara", "meaning": "goodbye", "example": "さようなら、また明日！", "example_translation": "Goodbye, see you tomorrow!"},
            {"word": "じゃあね", "reading": "じゃあね", "romaji": "Jaa ne", "meaning": "see ya (casual)", "example": "じゃあね！", "example_translation": "See ya!"},
        ],
        "grammar": [
            {"pattern": "〜です", "explanation": "Polite copula – equivalent to 'is/am/are'. Add to the end of sentences to make them polite.", "examples": [{"ja": "元気です", "en": "I am well"}, {"ja": "学生です", "en": "I am a student"}]},
            {"pattern": "〜ですか？", "explanation": "Add か to the end of a です sentence to make it a question.", "examples": [{"ja": "元気ですか？", "en": "Are you well?"}, {"ja": "学生ですか？", "en": "Are you a student?"}]},
        ],
        "conversation_scenario": {
            "setting": "You just landed at Narita Airport in Tokyo for your first trip to Japan. You walk up to the immigration counter and the friendly officer greets you.",
            "sensei_role": "Yuki, a friendly immigration officer at Narita Airport welcoming you to Japan",
            "learner_goal": "Greet the officer, respond when asked how you are, say thank you, and say goodbye",
            "starter_prompt": "こんにちは！Welcome to Japan! I'm Officer Yuki. Can you greet me back in Japanese?",
            "key_phrases": ["こんにちは", "元気ですか", "元気です", "ありがとうございます", "さようなら"],
        },
        "xp_reward": 100,
        "passing_score": 60,
    },
    {
        "id": "unit1_lesson2",
        "unit": 1,
        "order": 2,
        "title": "Self-Introduction",
        "title_ja": "自己紹介",
        "level": "N5",
        "type": "conversation",
        "description": "Introduce yourself with your name, nationality, and occupation",
        "objectives": [
            "Say your name using 〜です",
            "State your nationality",
            "Say よろしくお願いします",
        ],
        "vocabulary": [
            {"word": "私", "reading": "わたし", "romaji": "Watashi", "meaning": "I/me", "example": "私はアレックスです。", "example_translation": "I am Alex."},
            {"word": "名前", "reading": "なまえ", "romaji": "Namae", "meaning": "name", "example": "名前は何ですか？", "example_translation": "What is your name?"},
            {"word": "学生", "reading": "がくせい", "romaji": "Gakusei", "meaning": "student", "example": "私は学生です。", "example_translation": "I am a student."},
            {"word": "アメリカ人", "reading": "アメリカじん", "romaji": "Amerikajin", "meaning": "American person", "example": "私はアメリカ人です。", "example_translation": "I am American."},
            {"word": "よろしくお願いします", "reading": "よろしくおねがいします", "romaji": "Yoroshiku onegaishimasu", "meaning": "nice to meet you (polite)", "example": "アレックスです。よろしくお願いします。", "example_translation": "I'm Alex. Nice to meet you."},
            {"word": "お仕事", "reading": "おしごと", "romaji": "Oshigoto", "meaning": "work/job (polite)", "example": "お仕事は何ですか？", "example_translation": "What is your job?"},
        ],
        "grammar": [
            {"pattern": "私は〜です", "explanation": "Basic self-introduction pattern. 'I am ___.' Replace the blank with your name, nationality, or occupation.", "examples": [{"ja": "私はアレックスです", "en": "I am Alex"}, {"ja": "私はアメリカ人です", "en": "I am American"}]},
            {"pattern": "〜は何ですか？", "explanation": "'What is ___?' Use this to ask about someone's name, job, etc.", "examples": [{"ja": "名前は何ですか？", "en": "What is your name?"}, {"ja": "お仕事は何ですか？", "en": "What is your job?"}]},
        ],
        "conversation_scenario": {
            "setting": "First day at a Japanese language school in Tokyo. You meet a classmate in the hallway.",
            "sensei_role": "A Japanese university student named Yuki who is helping foreign students",
            "learner_goal": "Introduce yourself – name, where you're from, and that you're a student",
            "starter_prompt": "こんにちは！Welcome to the school! I'm Yuki. What's your name?",
            "key_phrases": ["私は〜です", "よろしくお願いします", "〜人です", "学生です"],
        },
        "xp_reward": 100,
        "passing_score": 60,
    },
    {
        "id": "unit1_lesson3",
        "unit": 1,
        "order": 3,
        "title": "Numbers 1-10",
        "title_ja": "数字",
        "level": "N5",
        "type": "vocabulary",
        "description": "Learn to count 1-10 and use numbers in simple contexts",
        "objectives": ["Count 1-10 in Japanese", "Say your age", "Ask someone's age"],
        "vocabulary": [
            {"word": "一", "reading": "いち", "romaji": "Ichi", "meaning": "one", "example": "一つだけください", "example_translation": "One please."},
            {"word": "二", "reading": "に", "romaji": "Ni", "meaning": "two", "example": "二人です。", "example_translation": "Two people."},
            {"word": "三", "reading": "さん", "romaji": "San", "meaning": "three", "example": "三時です。", "example_translation": "It's 3 o'clock."},
            {"word": "四", "reading": "し/よん", "romaji": "Shi / Yon", "meaning": "four", "example": "四月です。", "example_translation": "It's April."},
            {"word": "五", "reading": "ご", "romaji": "Go", "meaning": "five", "example": "五分です。", "example_translation": "It's 5 minutes."},
            {"word": "歳", "reading": "さい", "romaji": "Sai", "meaning": "years old", "example": "二十五歳です。", "example_translation": "I am 25 years old."},
        ],
        "grammar": [
            {"pattern": "〜歳です", "explanation": "Stating your age. Number + 歳 + です.", "examples": [{"ja": "二十歳です", "en": "I am 20 years old"}]},
            {"pattern": "何歳ですか？", "explanation": "Asking someone's age (can be rude to older people, use carefully).", "examples": [{"ja": "おいくつですか？", "en": "How old are you? (polite)"}]},
        ],
        "conversation_scenario": {
            "setting": "At a welcome party for new students. Playing a get-to-know-you number game.",
            "sensei_role": "Yuki, running a fun counting game for new students",
            "learner_goal": "Count 1-10, share your age, and ask Yuki's age",
            "starter_prompt": "OK everyone! Let's play a counting game to warm up. Can you count to five in Japanese for me?",
            "key_phrases": ["いち、に、さん、し、ご", "〜歳です", "何歳ですか"],
        },
        "xp_reward": 100,
        "passing_score": 60,
    },
    {
        "id": "unit2_lesson4",
        "unit": 2,
        "order": 1,
        "title": "What is This?",
        "title_ja": "これは何ですか",
        "level": "N5",
        "type": "conversation",
        "description": "Learn to ask and answer what things are using これ/それ/あれ",
        "objectives": ["Point at things and ask what they are", "Answer using 〜です", "Use これ/それ/あれ correctly"],
        "vocabulary": [
            {"word": "これ", "reading": "これ", "romaji": "Kore", "meaning": "this (near me)", "example": "これは本です。", "example_translation": "This is a book."},
            {"word": "それ", "reading": "それ", "romaji": "Sore", "meaning": "that (near you)", "example": "それは何ですか？", "example_translation": "What is that?"},
            {"word": "あれ", "reading": "あれ", "romaji": "Are", "meaning": "that (over there)", "example": "あれは学校です。", "example_translation": "That over there is a school."},
            {"word": "本", "reading": "ほん", "romaji": "Hon", "meaning": "book", "example": "これは日本語の本です。", "example_translation": "This is a Japanese book."},
            {"word": "ペン", "reading": "ペン", "romaji": "Pen", "meaning": "pen", "example": "それはペンです。", "example_translation": "That is a pen."},
            {"word": "電話", "reading": "でんわ", "romaji": "Denwa", "meaning": "phone/telephone", "example": "これは私の電話です。", "example_translation": "This is my phone."},
        ],
        "grammar": [
            {"pattern": "これ/それ/あれは〜です", "explanation": "Identifying objects. これ = near speaker, それ = near listener, あれ = far from both.", "examples": [{"ja": "これは本です", "en": "This is a book"}, {"ja": "それはペンですか？", "en": "Is that a pen?"}]},
        ],
        "conversation_scenario": {
            "setting": "Yuki is helping you unpack at your new apartment in Tokyo. She picks up items and asks about them.",
            "sensei_role": "Yuki, helping you organize your new apartment",
            "learner_goal": "Identify objects using これ/それ/あれ and practice asking 何ですか",
            "starter_prompt": "Your apartment is looking good! Oh, what's in this box? Let me help you unpack. これは何ですか？",
            "key_phrases": ["これは〜です", "それは何ですか", "あれは〜です"],
        },
        "xp_reward": 120,
        "passing_score": 60,
    },
    {
        "id": "unit2_lesson5",
        "unit": 2,
        "order": 2,
        "title": "Likes and Dislikes",
        "title_ja": "好きと嫌い",
        "level": "N5",
        "type": "conversation",
        "description": "Express what you like and dislike",
        "objectives": ["Say what you like using 好き", "Say what you dislike using 嫌い/好きじゃない", "Ask others about preferences"],
        "vocabulary": [
            {"word": "好き", "reading": "すき", "romaji": "Suki", "meaning": "like/fond of", "example": "寿司が好きです。", "example_translation": "I like sushi."},
            {"word": "嫌い", "reading": "きらい", "romaji": "Kirai", "meaning": "dislike", "example": "虫が嫌いです。", "example_translation": "I dislike bugs."},
            {"word": "大好き", "reading": "だいすき", "romaji": "Daisuki", "meaning": "love/really like", "example": "日本が大好きです！", "example_translation": "I love Japan!"},
            {"word": "食べ物", "reading": "たべもの", "romaji": "Tabemono", "meaning": "food", "example": "好きな食べ物は何ですか？", "example_translation": "What food do you like?"},
            {"word": "音楽", "reading": "おんがく", "romaji": "Ongaku", "meaning": "music", "example": "音楽が好きです。", "example_translation": "I like music."},
            {"word": "映画", "reading": "えいが", "romaji": "Eiga", "meaning": "movie/film", "example": "日本の映画が好きです。", "example_translation": "I like Japanese movies."},
        ],
        "grammar": [
            {"pattern": "〜が好きです", "explanation": "Expressing likes. Note: use が (not は) to mark what you like.", "examples": [{"ja": "猫が好きです", "en": "I like cats"}, {"ja": "コーヒーが好きです", "en": "I like coffee"}]},
            {"pattern": "好きな〜", "explanation": "Modifying nouns with 好き. 'Favorite ___' or '___ that I like'.", "examples": [{"ja": "好きな食べ物", "en": "food that I like / favorite food"}]},
        ],
        "conversation_scenario": {
            "setting": "At a café with Yuki after class. She asks about your interests over coffee.",
            "sensei_role": "Yuki, chatting with you at a cozy café near the language school",
            "learner_goal": "Talk about 3+ things you like or dislike, and ask Yuki about her preferences",
            "starter_prompt": "This café is so nice! I love coffee. コーヒーが大好きです！What about you – what do you like?",
            "key_phrases": ["〜が好きです", "〜が嫌いです", "好きなものは何ですか", "大好き"],
        },
        "xp_reward": 120,
        "passing_score": 60,
    },
    {
        "id": "unit2_lesson6",
        "unit": 2,
        "order": 3,
        "title": "Ordering Food",
        "title_ja": "注文",
        "level": "N5",
        "type": "conversation",
        "description": "Order food and drinks at a restaurant",
        "objectives": ["Order items with ください", "Ask for the menu", "Say what you want with ほしい"],
        "vocabulary": [
            {"word": "ください", "reading": "ください", "romaji": "Kudasai", "meaning": "please (give me)", "example": "水をください。", "example_translation": "Water, please."},
            {"word": "メニュー", "reading": "メニュー", "romaji": "Menyuu", "meaning": "menu", "example": "メニューをください。", "example_translation": "The menu, please."},
            {"word": "水", "reading": "みず", "romaji": "Mizu", "meaning": "water", "example": "お水をください。", "example_translation": "Water, please."},
            {"word": "ラーメン", "reading": "ラーメン", "romaji": "Raamen", "meaning": "ramen", "example": "ラーメンをください。", "example_translation": "Ramen, please."},
            {"word": "お会計", "reading": "おかいけい", "romaji": "Okaikei", "meaning": "the check/bill", "example": "お会計をお願いします。", "example_translation": "The check, please."},
            {"word": "おいしい", "reading": "おいしい", "romaji": "Oishii", "meaning": "delicious", "example": "このラーメンはおいしいです！", "example_translation": "This ramen is delicious!"},
        ],
        "grammar": [
            {"pattern": "〜をください", "explanation": "Politely requesting something. '(thing) please.' Use を to mark what you want.", "examples": [{"ja": "ラーメンをください", "en": "Ramen, please"}, {"ja": "お水をください", "en": "Water, please"}]},
            {"pattern": "〜をお願いします", "explanation": "Even more polite way to request. Used for services, not just items.", "examples": [{"ja": "お会計をお願いします", "en": "The check, please"}]},
        ],
        "conversation_scenario": {
            "setting": "Yuki takes you to a ramen shop in Shinjuku for your first real Japanese restaurant experience.",
            "sensei_role": "Yuki, showing you how to order at a ramen shop. She sometimes plays the waiter too.",
            "learner_goal": "Ask for a menu, order ramen and a drink, ask for the check",
            "starter_prompt": "Welcome to my favorite ramen shop! いらっしゃいませ！Let's sit down. Do you know how to ask for a menu in Japanese?",
            "key_phrases": ["メニューをください", "〜をください", "お会計をお願いします", "おいしい"],
        },
        "xp_reward": 130,
        "passing_score": 60,
    },
    {
        "id": "unit3_lesson7",
        "unit": 3,
        "order": 1,
        "title": "Asking Directions",
        "title_ja": "道を聞く",
        "level": "N5",
        "type": "conversation",
        "description": "Ask where things are and understand basic directions",
        "objectives": ["Ask where something is with どこですか", "Understand basic direction words", "Thank someone for directions"],
        "vocabulary": [
            {"word": "どこ", "reading": "どこ", "romaji": "Doko", "meaning": "where", "example": "トイレはどこですか？", "example_translation": "Where is the bathroom?"},
            {"word": "駅", "reading": "えき", "romaji": "Eki", "meaning": "train station", "example": "駅はどこですか？", "example_translation": "Where is the station?"},
            {"word": "右", "reading": "みぎ", "romaji": "Migi", "meaning": "right", "example": "右に曲がってください。", "example_translation": "Please turn right."},
            {"word": "左", "reading": "ひだり", "romaji": "Hidari", "meaning": "left", "example": "左にあります。", "example_translation": "It's on the left."},
            {"word": "まっすぐ", "reading": "まっすぐ", "romaji": "Massugu", "meaning": "straight ahead", "example": "まっすぐ行ってください。", "example_translation": "Please go straight."},
            {"word": "すみません", "reading": "すみません", "romaji": "Sumimasen", "meaning": "excuse me / sorry", "example": "すみません、駅はどこですか？", "example_translation": "Excuse me, where is the station?"},
        ],
        "grammar": [
            {"pattern": "〜はどこですか？", "explanation": "'Where is ___?' Basic location question.", "examples": [{"ja": "トイレはどこですか？", "en": "Where is the bathroom?"}, {"ja": "コンビニはどこですか？", "en": "Where is the convenience store?"}]},
        ],
        "conversation_scenario": {
            "setting": "You're lost in Shibuya trying to find the train station. You stop someone (Yuki!) on the street.",
            "sensei_role": "Yuki, a passerby you stop for directions near Shibuya crossing",
            "learner_goal": "Politely ask for directions to the station and understand the response",
            "starter_prompt": "You look a little lost! Can I help you? In Japanese, you can start by saying すみません to get someone's attention.",
            "key_phrases": ["すみません", "〜はどこですか", "右", "左", "まっすぐ", "ありがとうございます"],
        },
        "xp_reward": 130,
        "passing_score": 60,
    },
    {
        "id": "unit3_lesson8",
        "unit": 3,
        "order": 2,
        "title": "Time and Schedule",
        "title_ja": "時間",
        "level": "N5",
        "type": "conversation",
        "description": "Tell time and talk about daily schedules",
        "objectives": ["Ask and tell the time", "Say when you do things", "Talk about your daily routine"],
        "vocabulary": [
            {"word": "時", "reading": "じ", "romaji": "Ji", "meaning": "o'clock", "example": "三時です。", "example_translation": "It's 3 o'clock."},
            {"word": "半", "reading": "はん", "romaji": "Han", "meaning": "half past", "example": "七時半です。", "example_translation": "It's 7:30."},
            {"word": "朝", "reading": "あさ", "romaji": "Asa", "meaning": "morning", "example": "朝ごはんを食べます。", "example_translation": "I eat breakfast."},
            {"word": "今", "reading": "いま", "romaji": "Ima", "meaning": "now", "example": "今、何時ですか？", "example_translation": "What time is it now?"},
            {"word": "何時", "reading": "なんじ", "romaji": "Nanji", "meaning": "what time", "example": "何時に起きますか？", "example_translation": "What time do you wake up?"},
            {"word": "起きます", "reading": "おきます", "romaji": "Okimasu", "meaning": "wake up/get up", "example": "六時に起きます。", "example_translation": "I wake up at 6."},
        ],
        "grammar": [
            {"pattern": "〜時に", "explanation": "Indicating the time something happens. 'At ___ o'clock.'", "examples": [{"ja": "七時に起きます", "en": "I wake up at 7"}, {"ja": "八時に学校に行きます", "en": "I go to school at 8"}]},
            {"pattern": "何時ですか？", "explanation": "'What time is it?' or 'What time (does something happen)?'", "examples": [{"ja": "今、何時ですか？", "en": "What time is it now?"}]},
        ],
        "conversation_scenario": {
            "setting": "Yuki is planning a weekend study session and needs to coordinate schedules with you.",
            "sensei_role": "Yuki, planning weekend activities and asking about your schedule",
            "learner_goal": "Tell the time, share your daily schedule, and agree on a meeting time",
            "starter_prompt": "I want to plan a study session this weekend! 何時がいいですか？ What time works for you? First – do you know how to say the time in Japanese?",
            "key_phrases": ["何時ですか", "〜時に", "〜時半", "朝", "今"],
        },
        "xp_reward": 130,
        "passing_score": 60,
    },
    {
        "id": "unit3_lesson9",
        "unit": 3,
        "order": 3,
        "title": "Shopping",
        "title_ja": "買い物",
        "level": "N5",
        "type": "conversation",
        "description": "Ask about prices and buy things at a store",
        "objectives": ["Ask how much something costs", "Understand prices", "Buy things politely"],
        "vocabulary": [
            {"word": "いくら", "reading": "いくら", "romaji": "Ikura", "meaning": "how much", "example": "これはいくらですか？", "example_translation": "How much is this?"},
            {"word": "円", "reading": "えん", "romaji": "En", "meaning": "yen (Japanese currency)", "example": "百円です。", "example_translation": "It's 100 yen."},
            {"word": "高い", "reading": "たかい", "romaji": "Takai", "meaning": "expensive", "example": "ちょっと高いですね。", "example_translation": "It's a bit expensive."},
            {"word": "安い", "reading": "やすい", "romaji": "Yasui", "meaning": "cheap/inexpensive", "example": "安いですね！", "example_translation": "It's cheap!"},
            {"word": "買います", "reading": "かいます", "romaji": "Kaimasu", "meaning": "to buy", "example": "これを買います。", "example_translation": "I'll buy this."},
            {"word": "お土産", "reading": "おみやげ", "romaji": "Omiyage", "meaning": "souvenir/gift", "example": "お土産を買いたいです。", "example_translation": "I want to buy souvenirs."},
        ],
        "grammar": [
            {"pattern": "いくらですか？", "explanation": "'How much is it?' Essential shopping phrase.", "examples": [{"ja": "これはいくらですか？", "en": "How much is this?"}]},
            {"pattern": "〜を買います", "explanation": "'I'll buy ___.' Use を to mark what you're purchasing.", "examples": [{"ja": "これを買います", "en": "I'll buy this"}, {"ja": "お土産を買います", "en": "I'll buy a souvenir"}]},
        ],
        "conversation_scenario": {
            "setting": "Yuki takes you souvenir shopping in Asakusa near Senso-ji temple.",
            "sensei_role": "Yuki, your shopping guide at a souvenir shop. She sometimes plays the shopkeeper.",
            "learner_goal": "Ask prices of 2-3 items, react to prices (expensive/cheap), and buy something",
            "starter_prompt": "Welcome to Asakusa! Let's find some おみやげ for your friends back home. Look at all these shops! See anything you like?",
            "key_phrases": ["いくらですか", "〜円", "高い", "安い", "これを買います", "ください"],
        },
        "xp_reward": 140,
        "passing_score": 60,
    },
    {
        "id": "unit4_lesson10",
        "unit": 4,
        "order": 1,
        "title": "Free Conversation",
        "title_ja": "自由会話",
        "level": "N5",
        "type": "free_talk",
        "description": "Use everything you've learned in a natural conversation",
        "objectives": [
            "Have a 5-minute conversation using all learned vocabulary",
            "Self-correct when possible",
            "Ask Yuki questions back",
        ],
        "vocabulary": [],
        "grammar": [],
        "conversation_scenario": {
            "setting": "Your last day in Tokyo before heading home. Coffee with Yuki at the airport café.",
            "sensei_role": "Yuki, saying goodbye at the airport. Reminisce about your time together.",
            "learner_goal": "Have a natural conversation covering greetings, self-intro, likes, food, directions, time, shopping – anything from previous lessons",
            "starter_prompt": "I can't believe you're leaving already! 寂しくなりますね。Let's chat one more time over coffee. How has your time in Japan been? Tell me in Japanese!",
            "key_phrases": [],
        },
        "xp_reward": 200,
        "passing_score": 50,
    },
]


def get_lesson(lesson_id: str) -> dict:
    for lesson in LESSONS:
        if lesson["id"] == lesson_id:
            return lesson
    return LESSONS[0]


def get_all_lessons() -> list:
    return LESSONS


def get_next_incomplete_lesson(completed_ids: list[str]) -> dict:
    for lesson in LESSONS:
        if lesson["id"] not in completed_ids:
            return lesson
    return LESSONS[-1]
